---
ansible_command_timeout: 120
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/ansible.id_rsa
ansible_ssh_common_args: '-o UserKnownHostFile=/dev/null -o StrictHostKeyChecking=no -o KexAlgorithms=+diffie-hellman-group-exchange-sha1'
