---
- import_tasks: prepare.yml
  vars:
    ansible_network_os: junos
  when: "not is_fetch_only"

- import_tasks: deploy_edge.yml
  vars:
    ansible_network_os: junos
  when: "'edge_sw' in group_names and not is_overwrite and not is_fetch_only"

- import_tasks: deploy_core.yml
  vars:
    ansible_network_os: junos
  when: "'core_sw' in group_names and not is_overwrite and not is_fetch_only"

- import_tasks: overwrite.yml
  vars:
    ansible_network_os: junos
  when: "is_overwrite and not is_fetch_only"

- import_tasks: fetch.yml
  vars:
    ansible_network_os: junos
  when: "is_fetch_only"
