---
- name: Display all variables and facts stored in the inventory
  debug:
    var: hostvars[inventory_hostname]
  when: "not is_quiet and is_debug"

- name: Show version
  connection: network_cli
  junos_command:
    commands: show version
  when: "not is_quiet and is_debug"

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ snapshot_basedir }}"
    state: directory
  delegate_to: localhost
  no_log: "{{ is_quiet }}"
