---
- name: "Titanet4 Playbook Collection (see: https://github.com/yamaoka-kitaguchi-lab/tn4-player)"
  hosts: all
  gather_facts: no

  roles:
    - role: juniper
      when: manufacturer == "juniper"

    - role: cisco
      when: manufacturer == "cisco"
