---
- name: Create backup directory
  ansible.builtin.file:
    path: "backup/cisco_config.{{ datetime }}"
    state: directory
  register: local_dir
  delegate_to: localhost
  tags:
    - nondry

- name: Create pre-snapshots
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_before.cfg"
      dir_path: "backup/cisco_config.{{ datetime }}"
  tags:
    - nondry

- name: Check template rendering result
  debug:
    msg: "{{ lookup('template', 'overwrite.cfg.j2') }}"
  tags:
    - develop
    - rendering

- name: Overwrite configurations
  ios_config:
    src: overwrite.cfg.j2
    save_when: modified

- name: Create post-snapshots
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_after.cfg"
      dir_path: "backup/cisco_config.{{ datetime }}"
  tags:
    - nondry
