---
- name: Display all variables and facts stored in the inventory
  debug:
    var: hostvars[inventory_hostname]
  when: "{{ is_debug }}"
  tags:
    - develop
    - verbose

- name: Create backup directory
  ansible.builtin.file:
    path: "backup/cisco_config.{{ datetime }}"
    state: directory
  register: local_dir
  delegate_to: localhost
  tags:
    - nondry
